[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.8.21"
evm_version = "paris" # to prevent usage of PUSH0, which is not supported on all chains

optimizer = true
optimizer_runs = 1_000
verbosity = 3

[profile.default.fuzz]
runs = 100
max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail

[fmt]
  line_length = 120
  tab_width = 4
  bracket_spacing = false
  int_types = "long"
  multiline_func_header = "attributes_first"
  quote_style = "double"
  number_underscore = "preserve"
  wrap_comments = true
  ignore = ["test/*.sol"]